[target.x86_64-unknown-linux-musl]
image = "messense/rust-musl-cross:x86_64-musl"
[target.x86_64-unknown-linux-musl.env]
passthrough = [
  "OPENSSL_INCLUDE_DIR=/usr/local/musl/include",
  "OPENSSL_LIB_DIR=/usr/local/musl/lib",
  "RANLIB=/usr/local/bin/x86_64-linux-musl-ranlib",
]
