[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cipherstash/cli-multi-cross-build:latest"
env = { CC = "x86_64-linux-musl-gcc" }
rustflags = [
  "-C",
  "linker=x86_64-linux-musl-gcc",
  "-C",
  "target-feature=-crt-static",
]
