[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cipherstash/cli-multi-cross-build:latest"
platform = "linux/amd64"
[target.x86_64-unknown-linux-musl.env]
passthrough = [
  "OPENSSL_INCLUDE_DIR=/usr/local/musl/include",
  "OPENSSL_LIB_DIR=/usr/local/musl/lib",
  "RANLIB=/usr/local/bin/x86_64-linux-musl-ranlib",
]
