// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLLW-OPE order term — the `op` wire key. Backs the scalar `_ord_ope`
 * domains (`=` `<>` `<` `<=` `>` `>=`): a hex-encoded CLLW OPE ciphertext,
 * sortable via native bytea comparison after hex-decode — unlike `ob`
 * (block-ORE) and `oc` (CLLW-ORE) it needs no custom comparator. SQL-side
 * constructor: `eql_v3_internal.ope_cllw`. Distinct from [`OreCllw`] (`oc`), the
 * SteVec CLLW-*ORE* term compared by the custom per-byte protocol.
 */
export type OpeCllw = string;
