// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLLW-OPE order term — the `op` wire key. Backs the scalar `_ord` (the
 * default ordering domain), `_ord_ope`, and `text_search` domains, their
 * `query_` operands (`=` `<>` `<` `<=` `>` `>=`), and the ordered entries
 * of a SteVec document (exactly one of `hm` (equality) XOR `op` (ordering)
 * per entry — enforced by the SQL domain CHECK): a hex-encoded CLLW OPE
 * ciphertext, sortable via native bytea comparison after hex-decode —
 * unlike `ob` (block-ORE) it needs no custom comparator. Extracted by
 * `eql_v3.ord_term` (scalar domains and the `public.jsonb_entry` overload
 * alike); SQL-side constructor: `eql_v3_internal.ope_cllw`.
 */
export type OpeCllw = string;
