// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLLW-ORE ordered term — the `oc` wire key of a SteVec entry. Backs entry
 * ordering (`<` `<=` `>` `>=`) and equality on ordered leaves. SQL-side
 * constructor: `eql_v3.ore_cllw`. A SteVec entry carries exactly one of `hm`
 * (equality) XOR `oc` (ordering) — enforced by the SQL domain CHECK.
 */
export type OreCllw = string;
