// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ciphertext } from "./Ciphertext";
import type { Hmac256 } from "./Hmac256";
import type { OpeCllw } from "./OpeCllw";
import type { Selector } from "./Selector";

/**
 * `public.eql_v3_json_entry` — one sv element (returned by `->`). Carries a selector
 * `s`, ciphertext `c`, optional array-membership marker `a`, and exactly one of
 * `hm` XOR `op`. LAX (flatten precludes `deny_unknown_fields`): tolerates the
 * root `i`/`v` merged in by `->`. XOR of the term is enforced by the SQL CHECK.
 */
export type SteVecEntry = { s: Selector, c: Ciphertext, a?: boolean | null, } & ({ hm: Hmac256, } | { op: OpeCllw, });
