// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";
import type { SteVecEntry } from "./SteVecEntry";
import type { SteVecForm } from "./SteVecForm";

/**
 * `public.eql_v3_json` — a SteVec encrypted-JSONB document (`{v, k, i, sv:[entry]}`,
 * no root ciphertext). Strict. `k` is the `"sv"` form discriminator (see
 * [`SteVecForm`]) — carried on the real wire, so the strict struct models it.
 */
export type SteVecDocument = { v: SchemaVersion, k: SteVecForm, i: Identifier, sv: Array<SteVecEntry>, };
