// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hmac256 } from "./Hmac256";
import type { OpeCllw } from "./OpeCllw";
import type { Selector } from "./Selector";

/**
 * One element of a SteVec containment needle: a selector plus one term, and
 * (per the SQL CHECK) no ciphertext. LAX for the same flatten reason as
 * `SteVecEntry`; the "no `c`" contract is enforced by `is_valid_ste_vec_query_payload`.
 */
export type SteVecQueryEntry = { s: Selector, } & ({ hm: Hmac256, } | { op: OpeCllw, });
