// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hmac256 } from "./Hmac256";
import type { OpeCllw } from "./OpeCllw";

/**
 * The per-entry deterministic term: exactly one of `hm` (HMAC equality) or `op`
 * (CLLW-OPE ordering). Untagged — a document mixes both across its `sv` array.
 */
export type SteVecTerm = { hm: Hmac256, } | { op: OpeCllw, };
