// Generates the `@cipherstash/protect-ffi/wasm-inline` entry from wasm-pack output.
// Required because `--target bundler` emits `import * as wasm from "./*.wasm"`,
// which fails in runtimes that don't auto-bundle sibling `.wasm` assets
// (Supabase Edge, Cloudflare Workers without binding declarations, etc.).
//
// Ported from cipherstash-suite/packages/stack-auth/node/scripts/inline-wasm.mjs.

import { readFile, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const wasmDir = resolve(here, '..', 'dist', 'wasm')

const wasmBytes = await readFile(resolve(wasmDir, 'protect_ffi_bg.wasm'))
const base64 = wasmBytes.toString('base64')

// Reuse the export list wasm-pack itself wrote into the bundler stub —
// avoids drifting if new wasm-bindgen exports are added or renamed.
const bundlerStub = await readFile(resolve(wasmDir, 'protect_ffi.js'), 'utf-8')
const exportMatch = bundlerStub.match(
  /export\s*\{([\s\S]*?)\}\s*from\s*"\.\/protect_ffi_bg\.js";/,
)
if (!exportMatch) {
  throw new Error(
    'inline-wasm: could not parse export list from protect_ffi.js',
  )
}
const exportList = exportMatch[1].trim()

const shim = `/* @ts-self-types="./protect_ffi.d.ts" */
// Generated by scripts/inline-wasm.mjs — do not edit.

import * as bgImports from "./protect_ffi_bg.js";

const WASM_BYTES_B64 = "${base64}";
const wasmBytes = Uint8Array.from(atob(WASM_BYTES_B64), (c) => c.charCodeAt(0));

const { instance } = await WebAssembly.instantiate(wasmBytes, {
  "./protect_ffi_bg.js": bgImports,
});
bgImports.__wbg_set_wasm(instance.exports);
instance.exports.__wbindgen_start();

export {
${exportList}
} from "./protect_ffi_bg.js";
`

const outPath = resolve(wasmDir, 'protect_ffi_inline.js')
await writeFile(outPath, shim)

// wasm-pack `--target bundler` emits ESM (`import` / `export`) into
// `protect_ffi.js`, and the inline shim above is ESM too. The root
// `package.json` has no `"type": "module"`, so without a scoped marker
// Node would parse these as CJS and fail to load the `./wasm` and
// `./wasm-inline` subpath exports. Write a sibling `package.json` that
// scopes only `dist/wasm/**` as ESM; CJS semantics elsewhere are unchanged.
const pkgPath = resolve(wasmDir, 'package.json')
await writeFile(pkgPath, `${JSON.stringify({ type: 'module' }, null, 2)}\n`)

console.log(
  `inline-wasm: wrote protect_ffi_inline.js (${wasmBytes.length} wasm bytes -> ${base64.length} b64 chars) and package.json (type=module)`,
)
