services:
  postgres:
    image: postgres:latest
    container_name: protect-ffi-postgres
    environment:
      - POSTGRES_DB=${PGDATABASE:-cipherstash}
      - POSTGRES_USER=${PGUSER:-cipherstash}
      - POSTGRES_PASSWORD=${PGPASSWORD:-password}
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
